// ---------------------------------------------------------------------------
// Local demo stream — used only when the config module reports "mock".
//
// Why this exists: the capstone preview must let a reviewer hold a *streaming*
// conversation, and this machine has no ANTHROPIC_API_KEY. Rather than fake
// it in the client, this module emits the exact TextStreamPart chunks that a
// real streamText(...) produces (start -> reasoning* -> text-delta* -> finish).
// The route handler feeds this stream through the SAME toUIMessageStream /
// createUIMessageStreamResponse pipeline that the real Claude path uses, so
// every behaviour the brief cares about (visible token streaming, thinking
// indicator, markdown buffering, stop button, auto-scroll) is exercised on
// identical machinery. Point ANTHROPIC_API_KEY at the server and none of this
// code runs.
// ---------------------------------------------------------------------------

import { generateId } from "ai";
import type { TextStreamPart, UIMessage } from "ai";

const WORD_DELAY_MS = 22;

const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

/** Last user-visible text across the conversation, used by the mock reply. */
export function lastUserText(messages: UIMessage[]): string {
  for (let i = messages.length - 1; i >= 0; i -= 1) {
    const message = messages[i];
    if (message.role !== "user") continue;
    const text = message.parts
      .filter((part): part is Extract<UIMessage["parts"][number], { type: "text" }> => part.type === "text")
      .map((part) => part.text)
      .join(" ")
      .trim();
    if (text) return text;
  }
  return "this project";
}

/** "Thinking" preamble — exercises the reasoning part / indicator. */
function reasoningPreamble(topic: string): string {
  return `The reviewer is asking about "${topic}". Answering concisely with a code walkthrough and a short checklist, in markdown.`;
}

/** The demo answer, deliberately markdown-heavy to prove buffered rendering. */
function demoReply(topic: string): string {
  const t = topic.length > 40 ? `${topic.slice(0, 40)}…` : topic;
  return `Good question — here's how this streaming chat is wired up, with the pieces that matter for "${t}".

**The stack**

1. The route handler calls the model with \`streamText\`.
2. The AI SDK converts the model's text stream into UI-message chunks.
3. \`useChat\` on the client renders each \`text-delta\` part as it arrives.

\`\`\`ts
const result = streamText({ model, system, messages });
return createUIMessageStreamResponse({
  stream: toUIMessageStream({ stream: result.stream, sendReasoning: true }),
});
\`\`\`

> Note: this reply is generated by the local demo stream because no \`ANTHROPIC_API_KEY\` is set on the server. Deploy with the key and the identical UI streams from Claude itself.

Things that were verified while building it:

- Tokens visibly arrive one chunk at a time.
- Stop mid-stream keeps the partial reply and the input stays usable.
- Scrolling up releases the auto-scroll pin; \`Jump to latest\` re-pins it.
- The thinking indicator hands off to the first token with a fade, no flicker.`;
}

/**
 * Build a TextStreamPart stream that mirrors what streamText emits:
 * start -> reasoning-delta* -> text-delta* -> finish.
 * The stream is abortable (the client's "Stop" aborts the fetch, which
 * cancels this ReadableStream).
 */
export function mockTextStream(
  messages: UIMessage[],
): ReadableStream<TextStreamPart<Record<string, never>>> {
  const topic = lastUserText(messages);
  const reasoning = reasoningPreamble(topic);
  const reply = demoReply(topic);

  let cancelled = false;

  return new ReadableStream<TextStreamPart<Record<string, never>>>({
    start: async (controller) => {
      try {
        controller.enqueue({ type: "start" });

        const reasoningId = generateId();
        controller.enqueue({ type: "reasoning-start", id: reasoningId });
        for (const chunk of wordChunks(reasoning)) {
          if (cancelled) return;
          controller.enqueue({ type: "reasoning-delta", id: reasoningId, text: chunk });
          await sleep(14);
        }
        controller.enqueue({ type: "reasoning-end", id: reasoningId });

        const textId = generateId();
        controller.enqueue({ type: "text-start", id: textId });
        for (const chunk of wordChunks(reply)) {
          if (cancelled) return;
          controller.enqueue({ type: "text-delta", id: textId, text: chunk });
          await sleep(WORD_DELAY_MS);
        }
        controller.enqueue({ type: "text-end", id: textId });

        controller.enqueue({
          type: "finish",
          finishReason: "stop",
          rawFinishReason: "stop",
          totalUsage: {
            inputTokens: 0,
            inputTokenDetails: { noCacheTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 },
            outputTokens: Math.ceil(reply.length / 4),
            outputTokenDetails: { textTokens: Math.ceil(reply.length / 4), reasoningTokens: 0 },
            totalTokens: Math.ceil(reply.length / 4),
          },
        });

        controller.close();
      } catch {
        if (!cancelled) controller.error(new Error("mock stream failed"));
      }
    },
    cancel() {
      // Aborted mid-stream (Stop button / unmount): stop emitting immediately.
      cancelled = true;
    },
  });
}

/** Chunk a string into words with their trailing whitespace/newlines kept. */
function wordChunks(text: string): string[] {
  return text.match(/\S+\s*/g) ?? [text];
}