import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'

function App() {
  const [name, setName] = useState('Omar')

  return (
    <main className="mx-auto flex min-h-svh max-w-xl flex-col items-start justify-center gap-10 p-6">
      <header>
        <h1 className="text-2xl font-bold">shadcn/ui comparison</h1>
        <p className="text-muted-foreground">
          Same two widgets (dialog, tabs) generated by the shadcn CLI from the
          radix preset — open-code versions of the primitives that sit behind them.
        </p>
      </header>

      <section className="space-y-4">
        <h2 className="text-lg font-semibold">Dialog</h2>
        <Dialog>
          <DialogTrigger asChild>
            <Button>Open shadcn dialog</Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Edit profile</DialogTitle>
              <DialogDescription>
                shadcn wires DialogTitle/Description to aria-labelledby / aria-describedby.
              </DialogDescription>
            </DialogHeader>
            <label className="flex flex-col gap-1 text-sm font-medium">
              Display name
              <input
                value={name}
                onChange={(event) => setName(event.target.value)}
                className="rounded-md border border-input bg-background px-3 py-2 outline-none ring-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
              />
            </label>
            <DialogFooter>
              <Button type="submit">Save changes</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </section>

      <section className="w-full space-y-4">
        <h2 className="text-lg font-semibold">Tabs</h2>
        <Tabs defaultValue="overview">
          <TabsList>
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="details">Details</TabsTrigger>
            <TabsTrigger value="activity">Activity</TabsTrigger>
          </TabsList>
          <TabsContent value="overview" className="pt-3 text-muted-foreground">
            Arrow keys move between tabs; radix handles roving tabindex and activation.
          </TabsContent>
          <TabsContent value="details" className="pt-3 text-muted-foreground">
            Panels are hidden from the accessibility tree when inactive.
          </TabsContent>
          <TabsContent value="activity" className="pt-3 text-muted-foreground">
            Focus-visible rings come out of the box.
          </TabsContent>
        </Tabs>
      </section>
    </main>
  )
}

export default App